type LinkNameTo = {
  name: string;
  to: string;
  nameZn?: string;
};
export const link: LinkNameTo[] = [
  { name: 'expanding-cards', to: '/expanding-cards' },
  { name: 'progress-steps', to: '/progress-steps' },
  { name: 'rotating-navigation-animation', to: '/' },
  { name: 'hidden-search-widget', to: '/' },
  { name: 'blurry-loading', to: '/' },
  { name: 'scroll-animation', to: '/' },
  { name: 'split-panel', to: '/' },
  { name: 'form-wave', to: '/' },
  { name: 'sound-board', to: '/' },
  { name: 'dad-jokes', to: '/' },
  { name: 'event-keyCodes', to: '/' },
  { name: 'faq-collapse', to: '/' },
  { name: 'random-choice-picker', to: '/' },
  { name: 'animated-navigation', to: '/' },
  { name: 'incrementing-counter', to: '/' },
  { name: 'drink-water', to: '/' },
  { name: 'movie-app', to: '/' },
  { name: 'background-slider', to: '/' },
  { name: 'theme-clock', to: '/' },
  { name: 'button-ripple-effect', to: '/' },
  { name: 'drawing-app', to: '/' },
  { name: 'drag-n-drop', to: '/' },
  { name: 'content-placeholder', to: '/' },
  { name: 'kinetic-loader', to: '/' },
  { name: 'sticky-navbar', to: '/' },
  { name: 'double-slider', to: '/' },
  { name: 'toast-notification', to: '/' },
  { name: 'github-profiles', to: '/' },
  { name: 'double-click-heart', to: '/' },
  { name: 'auto-text-effect', to: '/' },
  { name: 'password-generator', to: '/' },
  { name: 'good-cheap-fast', to: '/' },
  { name: 'notes-app', to: '/' },
  { name: 'animated-countdown', to: '/' },
  { name: 'image-carousel', to: '/' },
  { name: 'hover-board', to: '/' },
  { name: 'pokedex', to: '/' },
  { name: 'mobile-tab-navigation', to: '/' },
  { name: 'password-strength-background', to: '/' },
  { name: '3d-background-boxes', to: '/' },
  { name: 'verify-account-ui', to: '/' },
  { name: 'live-user-filter', to: '/' },
  { name: 'feedback-ui-design', to: '/' },
  { name: 'custom-range-slider', to: '/' },
  { name: 'netflix-mobile-navigation', to: '/' },
  { name: 'quiz-app', to: '/' },
  { name: 'testimonial-box-switcher', to: '/' },
  { name: 'random-image-feed', to: '/' },
  { name: 'todo-list', to: '/' },
  { name: 'insect-catch-game', to: '/' },
];
